parameters:
    pim_catalog.resolver.fqcn.class:        Pim\Bundle\CatalogBundle\Resolver\FQCNResolver
    pim_catalog.resolver.user_locale.class: Pim\Bundle\CatalogBundle\Resolver\UserLocaleResolver

services:
    pim_catalog.resolver.fqcn:
        class: %pim_catalog.resolver.fqcn.class%
        arguments:
            - '@service_container'

    pim_catalog.resolver.user_locale:
        class: %pim_catalog.resolver.user_locale.class%
        arguments:
            - '@request_stack'
            - '@pim_localization.provider.date_format'
            - '@pim_localization.provider.number_format'
